docs: Add docs useful to new maintainers.
openedx/docs.openedx.org pull request #158
Opened 2022-10-12 14:12 UTC by feanil

Provide a basic checklist and a couple of quick how-tos for maintainers
newly starting to maintain a repo.

Relevant New Pages Rendered:

* https://docsopenedxorg--158.org.readthedocs.build/en/158/developers/how-tos/maintain-a-repo.html
* https://docsopenedxorg--158.org.readthedocs.build/en/158/developers/how-tos/add-a-catalog-file.html
* https://docsopenedxorg--158.org.readthedocs.build/en/158/developers/how-tos/enable-python-upgrade-automation.html

2022-10-13 14:17 UTC, mariajgrimaldi commented on source/developers/how-tos/add-a-catalog-file.rst
> +   backstage for your repository.
should we add something about permissions? or whoever is doing this is supposed to belong to the openedx org?

2022-10-13 14:38 UTC, mariajgrimaldi commented
Some other comments:

- Should we also link how to include codecov to the repo?  I once opened an [issue in openedx-events](https://github.com/openedx/openedx-events/issues/56), and some folks guided me to this document: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov. Maybe as other resources to take into consideration? Without its section. 

- A few days ago, we had to [update the repo](https://github.com/openedx/openedx-events/pull/126) metadata since it was marked as branched as an Open edX Release when it didn't need to be. 

- Also, I've been finding useful to check the cookie-cutter for updates to maintain our repo up-to-date, that's our good practice template.

- Should we add as a list the minimum of workflows for the repository?

2022-10-13 18:31 UTC, e0d approved these changes
I think this is generally great, I have some non-blocking feedback.  I stepped through the catalog-info creation and enabling the upgrade workflow in the xblock-drag-and-drop-v2 repo and everything was clear.

2022-10-13 18:31 UTC, e0d commented on source/developers/how-tos/add-a-catalog-file.rst
> +How To Add a Catalog File
I've stepped through these instructions and think they are good.

2022-10-13 18:31 UTC, e0d commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +3. Review the contets of the github action, make any changes that you might want
Are there any particular settings we think deserve attention?

2022-10-13 18:31 UTC, e0d commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +4. Commit the changes to a branch and get the PR reviewed and merged.
Maybe we should add a bit more specifics, or a screen shot, here as this isn't the default path.

![image](https://user-images.githubusercontent.com/1270274/195675616-2c0aa885-3d2b-435a-859d-400e2ba6d9fc.png)

2022-10-13 18:31 UTC, e0d commented on source/developers/how-tos/maintain-a-repo.rst
> +GitHub Issues is Enabeld
```suggestion
GitHub Issues is Enabled
```

2022-10-13 23:47 UTC, nedbat commented on source/developers/how-tos/add-a-catalog-file.rst
> +* You know how to use Git and GitHub PR Workflows
```suggestion
* You know how to use Git and GitHub PR Workflows.
```

2022-10-13 23:47 UTC, nedbat commented on source/developers/how-tos/add-a-catalog-file.rst
> +* You know how to edit YAML files
```suggestion
* You know how to edit YAML files.
```

2022-10-13 23:48 UTC, nedbat commented on source/developers/how-tos/add-a-catalog-file.rst
> +1. Go to your local clone of the repository you want to update.
These steps seem too basic.  Can't we say, "Add a catalog-info.yaml file to your repo, using the content from sample file..."?

2022-10-13 23:49 UTC, nedbat commented on source/developers/how-tos/add-a-catalog-file.rst
> +6. After the PR has merged, it can take up-to 90 minutes for backstage to pick
```suggestion
6. After the PR has merged, it can take up to 90 minutes for backstage to pick
```

2022-10-13 23:49 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +This How-to will walk you through the process of getting the automated python
```suggestion
This How-to will walk you through the process of getting the automated Python
```

2022-10-13 23:49 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +* You know how to use Git and GitHub PR Workflows
```suggestion
* You know how to use Git and GitHub PR Workflows.
```

2022-10-13 23:49 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +      :alt: An image of the Python Requiremnets Upgrade Workflow Card in Github's UI.
```suggestion
      :alt: An image of the Python Requirements Upgrade Workflow Card in GitHub's UI.
```

2022-10-13 23:50 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +3. Review the contets of the github action, make any changes that you might want
```suggestion
3. Review the contents of the GitHub action, make any changes that you might want
```

2022-10-13 23:51 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +      https://github.com/openedx/<repo_name>/actions/new?category=owner
Why are we using the GitHub UI for this, instead of telling them to create a file the usual way>

2022-10-13 23:52 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +   maintainer. Aspects such as being a good steward of the codebase, being a
```suggestion
   maintainer, such as being a good steward of the codebase, and being a
```

2022-10-13 23:52 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +excited to help you fullfill it.
```suggestion
excited to help you fulfill it.
```

2022-10-13 23:53 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +anything else.  If you *don't see an issues tab* then you see the ``Fix``
```suggestion
anything else.  If you *don't see an issues tab* then see the ``Fix``
```

2022-10-13 23:53 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +"Issues" box in the general settings.
Templates can be tricky. I think for now, it's fine to let people figure this out for themselves.

2022-10-13 23:54 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +you don't have a ``catalog-info.yaml`` file. See :doc:`add-a-catalog-file`
```suggestion
you don't have a ``catalog-info.yaml`` file, see :doc:`add-a-catalog-file`
```

2022-10-13 23:54 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +copy of `the upgrade workflow template`_.  You should also see successful runs
This is more what I expected for instructions: file-oriented, rather than UI-oriented.

2022-10-13 23:54 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +:doc:`enable-python-upgrade-automation`
```suggestion
:doc:`enable-python-upgrade-automation`.
```

2022-10-13 23:55 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +A Well Formed README Exists
```suggestion
A Well-Formed README Exists
```

2022-10-13 23:55 UTC, nedbat commented on source/developers/how-tos/maintain-a-repo.rst
> +Check that your readme exists and has all the sections defined in the `README
```suggestion
Check that your README.rst exists and has all the sections defined in the `README
```
(maybe?)

2022-10-13 23:55 UTC, nedbat requested changes
Minor tweaks

2022-10-14 18:44 UTC, nedbat commented on source/developers/how-tos/enable-python-upgrade-automation.rst
> +      https://github.com/openedx/<repo_name>/actions/new?category=owner
OK, let's try it like this.  My feeling when I've had GitHub pop open an editor for me to add a file (this just happened for dependabot.yml), is that I'm now not quite sure what will happen. Also, the later instruction say to check that the file is a correct copy, which will require them to go find where it is in our templates.

2022-10-14 20:29 UTC, nedbat approved these changes

2022-10-17 14:03 UTC, merged