Instructional Design Documentation
openedx/docs.openedx.org pull request #233
Opened 2022-12-21 14:47 UTC by jswope00

Adding discussed documentation for instructional Design:

Instructional Design Overview
Course Development Process
Instructional Design Templates

2022-12-21 14:48 UTC, openedx-webhooks commented
Thanks for the pull request, @jswope00!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-01-13 19:49 UTC, mphilbrick211 commented
Hi @jswope00! Just checking to see if this is ready for review?

2023-01-16 13:05 UTC, jswope00 commented
Hi @mphilbrick211 yes, this is ready to be reviewed and merged. Thanks!

2023-01-23 20:52 UTC, mphilbrick211 commented
Hi @feanil! Could you take a look at this?

2023-01-23 20:52 UTC, openedx-webhooks commented
@jswope00 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/233&entry.1484655318=https://github.com/jswope00&entry.752974735=2022-12-21+14:47&entry.1917517419=2023-01-23+20:52&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-01-23 20:53 UTC, mphilbrick211 commented
Sorry @feanil and @jswope00 - I closed this by accident - reopened for Feanil's review/merge.

2023-01-23 22:21 UTC, feanil commented
👍🏾 I'll review it in the next week or so hopefully.  Also adding @jmakowski1123 as a reviewer.

2023-01-27 16:11 UTC, feanil requested changes
This is really awesome, for the most part this looks ready to land to me, just two small things that need to be updated before it's ready to go.

* source/_images/instructional_design/addie_model.png can you update this to remove the curricu.me logo?
* I've updated the URLs for the templates so that they're hosted by tCRIL, can you accept those changes?

2023-01-27 16:11 UTC, feanil commented on source/educators/concepts/instructional_design/id_templates.rst
> +`Download Grading Chart <https://docs.google.com/spreadsheets/d/1LjWAM5N5nFLMTNdFCDjq23ffJTDG-BH81jNjHrWusj0/edit?usp=sharing>`_
```suggestion
`Download Grading Chart <https://docs.google.com/spreadsheets/d/1wq3tlIXNqZyy0bL2Dn8hgO9UY0xQMwGbhct_MQ9DSZc/edit#gid=1193955468>`_
```

2023-01-27 16:11 UTC, feanil commented on source/educators/concepts/instructional_design/id_templates.rst
> +`Download Quality Control Template <https://docs.google.com/document/d/1ihzP51X26sU7yONFcRt8LBjvG1iXGM51VX9GT234fbQ/edit?usp=sharing>`_
```suggestion
`Download Quality Control Template <https://docs.google.com/document/d/1zWYVCI_M39-bHjaqoerGgVuD4_ZursvabzJSNLQBs9s/edit?usp=share_link>`_
```

2023-01-27 16:11 UTC, feanil commented on source/educators/concepts/instructional_design/id_templates.rst
> +`Download Sample Communication Plan <https://docs.google.com/document/d/1b043Z85tq4oJQLmrADmiVOHdkMn4F9on/edit?usp=sharing&ouid=102215557727623303211&rtpof=true&sd=true>`_
```suggestion
`Download Sample Communication Plan <https://docs.google.com/document/d/1-ooDKyWrLvj6Z2pRud7douMEtPbHc69K/edit?usp=share_link&ouid=106462470317905634700&rtpof=true&sd=true>`_
```

2023-01-27 16:11 UTC, feanil commented on source/educators/concepts/instructional_design/id_templates.rst
> +`Download Support Calendar <https://docs.google.com/spreadsheets/d/1LjWAM5N5nFLMTNdFCDjq23ffJTDG-BH81jNjHrWusj0/edit?usp=sharing>`_
```suggestion
`Download Support Calendar <https://docs.google.com/spreadsheets/d/1wq3tlIXNqZyy0bL2Dn8hgO9UY0xQMwGbhct_MQ9DSZc/edit#gid=2000240391>`_
```

2023-01-31 02:12 UTC, jswope00 commented
@feanil and @jmakowski1123 changes made!

2023-02-06 16:18 UTC, feanil approved these changes
Looks great, thanks @jswope00!

2023-02-06 16:57 UTC, jmakowski1123 approved these changes
@feanil I checked all the template links and I'm able to edit the word docs. Is that because I have access to the drive, or are they not set to read only? Other than that, looks good!

2023-02-06 17:21 UTC, feanil commented
@jmakowski1123 that is because you have access to the drive, I've confirmed that anonymous users only have read access.

2023-02-06 17:21 UTC, merged

2023-02-06 17:21 UTC, openedx-webhooks commented
@jswope00 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/233&entry.1484655318=https://github.com/jswope00&entry.752974735=2022-12-21+14:47&entry.1917517419=2023-02-06+17:21&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->