Mh documentors section update
openedx/docs.openedx.org pull request #27
Opened 2022-05-24 23:50 UTC by markH-Docemus

2022-05-25 15:12 UTC, feanil requested changes
Generally seems like great improvements. A couple of suggested fixes and also it looks like we added the `.DS_Store` file in accidentally on a previous commit and it should be removed.

2022-05-25 15:12 UTC, feanil commented on source/creating_doc/doc_home.rst
> +   :doc:`references/doc_guidelines`
These need bullets or a blank line between them because otherwise multiple links are showing up on the same line without any clear separation.

2022-05-27 14:00 UTC, openedx-webhooks commented
Thanks for the pull request, @markH-Docemus! I've created [OSPR-6736](https://openedx.atlassian.net/browse/OSPR-6736) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-05-27 14:07 UTC, natabene commented
@markH-Docemus Thank you for your contribution. Once your have submitted the CLA forms and they have been processed, we will be able to merge your PR.

2022-05-31 18:12 UTC, feanil approved these changes
I think there is still some more improvements to make in the forking stuff because if you're forking for the first time it's a different experience but I think this is already a pretty big PR so we should land these changes and then iterate more on the intro for the documentors section.

2022-06-07 14:58 UTC, merged

2022-06-07 14:58 UTC, openedx-webhooks commented
@markH-Docemus 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/27&entry.1484655318=https://github.com/markH-Docemus&entry.752974735=2022-05-24+23:50&entry.1917517419=2022-06-07+14:58&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->