docs: Add maintainer community standards
openedx/docs.openedx.org pull request #476
Opened 2024-03-07 20:17 UTC by arbrandes

### Description

Adds a few explicit community standards for maintainers in the repo maintenance howto.

2024-03-11 17:10 UTC, sarina requested changes

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +  and screenshots: anybody should be able to gleen from them not only the How,
```suggestion
  and screenshots: anybody should be able to understand not only the How,
```
"glean" feels a bit obscure for all the ESL folk in our community

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +  a big no-no!
```suggestion
  a big no-no! Hint: Try viewing your link in an incognito browser to see if it is publicly available.
```

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +* Just because you've been entrusted with write access, it doesn't mean you
```suggestion
* Just because you've been entrusted with write access doesn't mean you
```

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +  channels - Discourse, Slack, working group meetings, and, of course, Github
Should we make Discourse & Slack links? eg https://discuss.openedx.org/ and https://openedx.org/slack

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +.. note::
```suggestion
.. important::
```
I think this may be a better callout!

2024-03-11 17:10 UTC, sarina commented on source/developers/how-tos/maintain-a-repo.rst
> +   beforehand.
```suggestion
   beforehand; even if a feature is by default not shown, experimental code causes cognitive, testing, and potentially even release-impacting burdens.
```

I don't know if this is the right wording, but I think it's important to be explicit about the "why must this be approved"

2024-03-12 13:43 UTC, arbrandes commented
Thanks for the review @sarina!  I've addressed your comments.

2024-03-12 16:13 UTC, sarina approved these changes

2024-03-13 18:31 UTC, feanil reviewed
This is a great concise addition to the docs, I think it should go at the top of the ongoing maintainer responsibilities section.  Once it's moved, I think this is good to merge!

2024-05-15 15:57 UTC, merged