fix: Import Export course content
openedx/docs.openedx.org pull request #502
Opened 2024-06-05 08:42 UTC by CodeWithEmad

I was reading this section and noticed some issues.

- images are updated
- content changed a bit for better readability
- 1 outdated/redirected link fixed.

2024-06-10 15:37 UTC, jswope00 commented on source/educators/migration_wip/images/course_export_page.png
The deleted image in this case is the new MFE, whereas the new image shows the old non-MFE front-end. We want the docs to use the latest front-ends, so this change should be reverted.

2024-06-10 15:44 UTC, jswope00 requested changes
Thanks for your suggestions! I have a few comments inline that need to be addressed and then I think this is good.

2024-06-10 15:44 UTC, jswope00 commented on source/educators/migration_wip/images/course_import_page.png
The deleted image in this case is the new MFE, whereas the new image shows the old non-MFE front-end. We want the docs to use the latest front-ends, so this change should be reverted.

2024-06-10 15:44 UTC, jswope00 commented on source/educators/migration_wip/15_releasing_course/export_import_course.rst
> +export your course and open the **.xml** files for editing. The following table
I think yes, this should also be double backticked.

2024-06-10 15:44 UTC, jswope00 commented on source/educators/migration_wip/images/course_export_page.png
See this comment.

2024-06-11 06:35 UTC, CodeWithEmad commented on source/educators/migration_wip/15_releasing_course/export_import_course.rst
> +export your course and open the **.xml** files for editing. The following table
fixed

2024-06-11 14:47 UTC, jswope00 approved these changes
Approved!

2024-06-11 14:47 UTC, merged

2024-06-11 14:47 UTC, openedx-webhooks commented
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/502&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2024-06-05+08:42&entry.1917517419=2024-06-11+14:47&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->