feat: add TX snippet
openedx/docs.openedx.org pull request #68
Opened 2022-07-12 18:41 UTC by ghassanmas

~~This is work in progress.~~

It suppose to add JS script of TX JS within the Head tag. 
This snippet is need to test TX live: 
Ref: https://docs.transifex.com/live/installing-the-javascript-snippet
﻿
CC: Eden Huthmacher @ehuthmacher

2022-07-12 18:41 UTC, openedx-webhooks commented
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-07-12 19:43 UTC, feanil requested changes
Generally looks good, a couple of changes and then I think we can merge this.

2022-07-12 19:43 UTC, feanil commented on source/_templates/layout.html
> +{% extends "!layout.html" %} {% block extrahead %}
```suggestion
{# Add content to the <head> tag.  See https://www.sphinx-doc.org/en/master/templating.html for more details #}
{% extends "!layout.html" %} {% block extrahead %}
```

2022-07-13 13:44 UTC, feanil approved these changes

2022-07-13 13:44 UTC, merged

2022-07-13 13:44 UTC, openedx-webhooks commented
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/68&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-07-12+18:41&entry.1917517419=2022-07-13+13:44&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->