FC-0068: Adding and converting txt files into rst format
openedx/docs.openedx.org pull request #699
Opened 2024-12-19 19:19 UTC by jesgreco

adding and cleaning up for  create_unit.rst

2024-12-19 19:19 UTC, openedx-webhooks commented
Thanks for the pull request, @jesgreco!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/docs-openedx-org-maintainers`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-12-20 21:18 UTC, jswope00 requested changes
You have "duplicate label" warnings in your build. They are coming because we already have "create a section", "create a subsection", and "create a unit" targets. 

So the question becomes where you got these instructions from? I think you got them from the old .txt files, and didn't write this anew? 

In that case, the short term fix might be to give these unique target names. But please bring this up in your next meeting, because this is a scenario where we have two very overlapping how-tos, and we should fix that together.

2024-12-26 18:08 UTC, jesgreco commented
@jswope00 ok! I'll write this in our channel to see if we can have a solution before the next meeting which will be 8th January.

2024-12-27 16:21 UTC, jesgreco commented
@jswope00 I've solved the conflict for merging but, still we need to solve the label duplication.

2024-12-27 16:22 UTC, jesgreco commented
@jswope00 I've solved the conflict for merging but, still we need to solve the label duplication.

2025-01-08 14:13 UTC, jswope00 commented
We have duplicate files and labels for "Create a Subsection" "Create a Section" and "Create a Unit". Here is what needs to happen here. 

1. Manually merge each (section, subsection, unit) into one golden-copy file. 
2. Delete the extra files and labels. 
3. If we need to include a particular section in another file, then use this method: https://docs.openedx.org/en/latest/documentors/references/templates/doc_quickstart_template.html#how-to-embed-only-a-section

2025-01-09 19:30 UTC, jesgreco commented
@jswope00 I've deleted the duplicated files, and try to include one single file (create.rst) but, then I've realized they are all included. So, there is no need to include a "golden-copy" file. Let me know if you agree on this.

2025-01-09 21:33 UTC, jswope00 commented
Just to clarify this commit for anyone looking at it in the future. 
It essentially deletes two files: 
- create_section.rst
- create_subsection.rst

Because those files already exist as create_hide_delete_sections.rst and create_edit_publish_subsections.rst. So this removes the redundancy.

2025-01-09 21:33 UTC, jswope00 approved these changes

2025-01-09 21:34 UTC, jswope00 commented
@jesgreco can you resolve the conflicts on this one?

2025-01-10 17:16 UTC, jesgreco commented
so, I assume we can proceed with this PR to be merged.

2025-01-14 12:22 UTC, jesgreco commented
I believe we should delete this PR since there were duplication of files within this PR, and now no changes are included in this PR. If we delete the PR, those conflicts should be solved (and I cannot solve them since I don't have write access).

2025-01-15 18:22 UTC, jswope00 commented
This PR has a lot of commits that could be confusing if trying to parse through them in the future, and ultimately no changes were made. I propose closing it without merging.

2025-01-15 18:22 UTC, closed without merging