FC-0068 docs: Reference cleaning by edunext #6
openedx/docs.openedx.org pull request #708
Opened 2024-12-23 05:18 UTC by Apgomeznext

This PR modifies a series of reference documents migrated from the legacy repositories to the educators' documentation.

The principal changes are in the Access_ORA_Info, divided into 5 how-tos and a reference. Also, I added some content in the multiple_choice to adapt that page to the parameters defined in the Style Guide.

2024-12-23 05:18 UTC, openedx-webhooks commented
Thanks for the pull request, @Apgomeznext!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.


#### :radio_button: Update the status of your PR

Your PR is currently marked as a draft.  After completing the steps above, update its status by clicking "Ready for Review", or removing "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/docs-openedx-org-maintainers`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2025-01-06 12:31 UTC, sarina requested changes

2025-01-06 12:31 UTC, sarina commented on source/educators/how-tos/course_development/exercise_tools/list_manage_students_waiting_peer_step.rst
> +waiting peer responses to evaluate or peer reviews from other learners indefinitely.
```suggestion
waiting for peer responses to evaluate, or for peer reviews from other learners, indefinitely.
```

2025-01-06 12:31 UTC, sarina commented on source/educators/references/course_development/exercise_tools/multiple_choice.rst
> +The Multiple-Choice Problem in Open edX is a commonly used question type that allows learners to select one or more answers from a predefined list of options. It is highly versatile and can be employ
```suggestion
The Multiple-Choice Problem is a commonly used question type that allows learners to select one or more answers from a predefined list of options. It is highly versatile and can be employed to test knowledge, reinforce learning, or assess understanding in various subjects.
```

2025-01-08 23:10 UTC, Apgomeznext commented
@sarina, the requested changes were applied, and the conflicts were solved. It is ready for merge :)

2025-01-09 00:28 UTC, sarina approved these changes

2025-01-09 00:28 UTC, merged