FC-0068 docs: Concept cleaning by edunext #11
openedx/docs.openedx.org pull request #716
Opened 2024-12-31 16:09 UTC by BryanttV

This PR modifies a series of concept documents migrated from the legacy repositories to the educators' documentation.

2024-12-31 16:09 UTC, openedx-webhooks commented
Thanks for the pull request, @BryanttV!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/docs-openedx-org-maintainers`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2025-01-06 13:27 UTC, sarina commented
@BryanttV is this ready for review?

2025-01-07 21:08 UTC, sarina requested changes
I only reviewed the first file. Please take a look through my comments, and update following documents appropriately before requesting a re-review. Particularly, "Open edX" should be used as an adjective, should *not* be capitalized as "Open Edx", and some judgement should be applied when to use something like "your Open edX instance" or simply "your instance".

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
>   supported for new users.
Please remove this note, it was applicable to edx.org but not to the community.

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +When you use LTI to reuse Open edX course content, learners who are already
```suggestion
When you use LTI to reuse your course content, learners who are already
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +application (external LMS) see content from Open edX that is seamlessly
```suggestion
application (external LMS) see content from your Open edX instance that is seamlessly
```

Open edX should always be used as an adjective.

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +integrated into a familiar context. Only the content that you specify from Open
```suggestion
integrated into a familiar context. Only the content that you specify from your Open
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +edX appears in the external LMS, typically within an iframe on a page.
```suggestion
edX instance appears in the external LMS, typically within an iframe on a page.
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +include a link to a problem component that is part of an Open edX course. The
```suggestion
include a link to a problem component that is part of a course on your instance. The
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
>    .. note:: Different configuration options are available for how an external
Remove this note entirely

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +other system (including Open edX), to access content that originates in an Open
```suggestion
other system (including your Open edX instance), to access content that originates in a
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +edX course. However, the first time a learner views Open edX course content in
```suggestion
course on your instance. However, the first time a learner views Open edX course content in
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +experience in the future. However, this separate Open edX identifier can make
```suggestion
experience in the future. However, this separate identifier can make
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +some Open edX content confusing for learners when viewed in the context of an
```suggestion
some content confusing for learners when viewed in the context of an
```

2025-01-07 21:08 UTC, sarina commented on source/educators/concepts/advanced_features/lti_reuse_content.rst
> +participants by their Open edX IDs instead of the usernames they would normally
```suggestion
participants by these unique IDs instead of the usernames they would normally
```

2025-01-07 23:29 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
Here, please change the paragraph for the following:
"Learners cannot upload file types with the following file name extensions as part of an Open Response Assessment. When you define a set of custom file types for learners to upload with their responses, you cannot specify them. The extensions on this list are selected and maintained by the development operations team at the Open edX Community and are subject to change."

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
>    recommends a setting such as **Must Grade** = 4 and **Graded By** = 3.
Replace Open edX as the subject with Open edX Community.

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +Open edX suggests that you follow the guidelines and best practices in the
Replace Open edX as the subject with Open edX Community.

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +entire response.) Open edX recommends that you specify 20 or fewer responses to
Replace Open edX as the subject with Open edX Community.

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +.. note:: Given the high level of subjectivity in peer assessments, Open edX
Replace Open edX as the subject with Open edX Community.

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +you place the peer assessment before the self assessment.
Replace Open edX as the subject with Open edX Community.

2025-01-07 23:32 UTC, Apgomeznext commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +   edX recommends that you place the peer assessment before the self
Replace Open edX as the subject with Open edX Community.

2025-01-08 23:07 UTC, sarina requested changes

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +When you include the problem components in a graded Open edX subsection in an
I would rewrite this paragraph because it is confusing, it talks about "Open edX" as a thing when really it needs to be discussing your specific Open edX instance.

When you include problem components from a graded subsection in your Open edX instance in an external LMS, your Open edX instance will grade the learner responses to those problems. Your instance then transfers the learner scores back to the external LMS. This exchange between an external LMS, your Open edX instance, and the external LMS again is near real time. It can take a few moments to complete this exchange for a single problem component, and up to several minutes to return aggregated scores of all the problems in a unit or subsection.

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +When you include Open edX problem components in an external LMS, note the
```suggestion
When you include problem components from your Open edX instance in an external LMS, note the
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +* The Open edX problem component must be in one of the graded subsections in
```suggestion
* The problem component must be in one of the graded subsections in
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> + :ref: `edX as an LTI Provider to Blackboard` (reference)
Same here

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +If you include both peer and self assessment steps, the Open edX Community
```suggestion
If you include both peer and self assessment steps, it is
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +recommends that you place the peer assessment before the self assessment.
```suggestion
recommended that you place the peer assessment before the self assessment.
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +If you include both peer and self assessments, the Open edX Community
```suggestion
If you include both peer and self assessments, it is
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +recommends that you include the peer assessment before the self assessment.
```suggestion
recommended that you include the peer assessment before the self assessment.
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +.. note:: Given the high level of subjectivity in peer assessments, the Open
```suggestion
.. note:: Given the high level of subjectivity in peer assessments,
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +   edX Community recommends that you make ORA assignments count towards only a
```suggestion
   it is recommended that you make ORA assignments count towards only a
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +entire response.) The Open edX Community recommends that you specify 20 or
```suggestion
entire response.) It is recommended that you specify 20 or
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +The Open edX Community suggests that you follow the guidelines and best
```suggestion
It is suggested that you follow the guidelines and best
```

2025-01-08 23:07 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +part of and Open Response Assessment. When you define a set of custom file
```suggestion
part of an Open Response Assessment. When you define a set of custom file
```

2025-01-08 23:17 UTC, Apgomeznext commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> + :ref: `edX as an LTI Provider to Canvas` (reference)
This reference is the Open edX repository, but the tag name of that file wasn't modified to prevent the broken links.

2025-01-09 16:19 UTC, BryanttV commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> + :ref: `edX as an LTI Provider to Blackboard` (reference)
I updated the references to use the correct tags: https://github.com/openedx/docs.openedx.org/commit/4daafbefe0c1a5fe96468761e5ca1a414ebd0f0e. Thanks!

2025-01-09 16:20 UTC, BryanttV commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +When you include the problem components in a graded Open edX subsection in an
Thanks, I applied your suggestion: https://github.com/openedx/docs.openedx.org/commit/d88c241ceb33281bd7e9ac22d75b9507b8bca4c0

2025-01-09 16:28 UTC, BryanttV commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +When you include Open edX problem components in an external LMS, note the
Updated: https://github.com/openedx/docs.openedx.org/commit/1d2621d9e9db966284fd6c0fc9c8f9c04825af21

2025-01-09 16:28 UTC, BryanttV commented on source/educators/concepts/advanced_features/using_openedx_as_LTI_provider.rst
> +* The Open edX problem component must be in one of the graded subsections in
Updated: https://github.com/openedx/docs.openedx.org/commit/1d2621d9e9db966284fd6c0fc9c8f9c04825af21

2025-01-09 17:28 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +   edX recommends that you place the peer assessment before the self
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:28 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +If you include both peer and self assessment steps, the Open edX Community
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:28 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +recommends that you place the peer assessment before the self assessment.
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:28 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +If you include both peer and self assessments, the Open edX Community
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:29 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +.. note:: Given the high level of subjectivity in peer assessments, the Open
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:29 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +   edX Community recommends that you make ORA assignments count towards only a
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:29 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +entire response.) The Open edX Community recommends that you specify 20 or
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:29 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +The Open edX Community suggests that you follow the guidelines and best
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-09 17:29 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> +operations team at the Open edX Community and are subject to change.
Updated: https://github.com/openedx/docs.openedx.org/commit/c87cb858aa0bd7b3d365eaab7732784687bfc8c0

2025-01-10 16:30 UTC, sarina commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> -change.
Please only remove the _last_ sentence ("The extensions on this list are selected and
maintained by the development operations team at edX, and are subject to
change."), not the whole paragraph.

2025-01-10 17:59 UTC, BryanttV commented on source/educators/concepts/exercise_tools/OpenResponseAssessments.rst
> -change.
Done: https://github.com/openedx/docs.openedx.org/commit/72a1b1da6743ab296557c7069f02a23a4d361afa

2025-01-13 22:43 UTC, sarina approved these changes

2025-01-13 22:43 UTC, sarina commented
@BryanttV - there are conflicts in this PR - please resolve and ping me for merge.

2025-01-14 22:03 UTC, merged